config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users

  root to: 'records#index'
  resources :records
  

  
  match ':controller(/:action(/:id))', :via => :get
end

app/models/record.rb
class Record < ActiveRecord::Base
  validates :title, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :added_by, presence: true
  scope :search, ->(search) {  where ("search_vector @@ to_tsquery('#{search}')") }

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable
  
  def update_geodata!
    geo = geocode
    if geo.success
      self.lat, self.lng = geo.lat,geo.lng
      self.save!
    end
  end
  
  def geocode
    geodata = Geokit::Geocoders::MultiGeocoder.geocode(full_address)
    
  end
  
  def full_address
    "#{street} #{suite} #{city} #{state} #{postal}".squish
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  
  # GET /records
  # GET /records.json
  def index
     puts params.to_json
    if (params[:search])
      @records = Record.search(params[:search])
    else 
      @records = Record.all
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:title, :category, :description, :created_date, :added_by)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="current_user" >
<% if current_user %>
    <span>Logged in as: <strong><%= current_user.email %></strong></span>
<% end %>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/records/_form.html.erb
<%= simple_form_for(@record) do |f| %>
  <%= f.input :title %>
  <%= f.input :category %>
  <%= f.input :description %>
  <%= f.input :added_by, input_html: { maxlength: 20,  value: current_user.email, readonly: 'readonly' } %>
  <%= f.input :created_date %>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>
<div class='results'>
<table data-initialized="false">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Description</th>
      <th>Added By</th>
      <th>Created date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.title %></td>
        <td><%= record.category %></td>
        <td><%= record.description %></td>
        <td><%= record.added_by %></td>
        <td><%= record.created_date %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>
<div class='results'>

<div class='functions'>
 <%= form_tag(records_path, method: 'get') do %>
<ul> 
<li><%= link_to 'New Record', new_record_path %></li>
<li class="highlight search"><%= text_field_tag :search, params[:search], placeholder: 'Search Records', type: :search, style: 'width: 250px' %></li>
<li><%= submit_tag "Search", :name => nil %> &nbsp; </li>
</ul>
<% end %> 
</div>
<script>
$(document).ready(function(){
    var $table = $('.results table');
    if ($table && $table.length && (typeof $table.attr('data-initialized') !== 'string' || $table.attr('data-initialized') === 'false')){
        $('.results table').attr('data-initialized','true').dataTable({
         "aoColumnDefs": [
                { 'bSortable': false, 'aTargets': [ 5,6,7 ] }
            ]
        });
    }
});

</script>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<div class="record">
<p>
  <strong>Title:</strong>
  <%= @record.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @record.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @record.description %>
</p>

<p>
  <strong>Created date:</strong>
  <%= @record.created_date %>
</p>
</div>
<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/records/show.html.slim
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @record.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @record.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @record.description %>
</p>

<p>
  <strong>Created date:</strong>
  <%= @record.created_date %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>